# Uncomment the next line to define a global platform for your project

    platform :ios, '14.0'
    use_frameworks!

target 'cocotton-frontend' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for cocotton-frontend
  
  pod 'SwiftKeychainWrapper', '~> 4.0'

  target 'cocotton-frontendTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cocotton-frontendUITests' do
    # Pods for testing
  end

end
